build: false

environment:
  matrix:
    # - TOXENV: py37
    #   PYTHON: "C:\\Python37-x64"
    #   PYTHON_VERSION: "3.7.0"
    #   PYTHON_ARCH: "64"

    - TOXENV: py37
      PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"

    # - TOXENV: py27
    #   PYTHON: "C:\\Python27"
    #   PYTHON_VERSION: "2.7.0"
    #   PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "%PYTHON%\\python.exe --version"

# tox installs stuff itself.
install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install -r requirements.dev.txt"
  - "%PYTHON%\\python.exe setup.py bdist_msi"
  - ps: "ls dist"

test_script:
  # - "%PYTHON%\\python.exe -m tox"
  - "%PYTHON%\\python.exe -m pytest"

# https://www.appveyor.com/docs/packaging-artifacts/
artifacts:
  - path: dist\*.msi
    name: windows msi executable

# For uploading releases to github.
# https://www.appveyor.com/docs/deployment/github/
deploy:
  # description: 'A parrotjoy draft release'
  provider: GitHub
  auth_token:
    secure: AEkY1NaqqAq8NhWj7xNY+meHJINhLrnHNpwEeVtKBsAhdxo7u34gNsTH+KcYJUho # your encrypted token from GitHub
  artifact: windows msi executable
  draft: true
  prerelease: false
  force_update: true
  on:
    # branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

